import Head from 'next/head';
import Image from 'next/image';
import Link from '../components/Link';
import styles from '../styles/Home.module.css';

import { getAllPosts } from '../Utils/Posts/posts';

export default function Home({ allPosts }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Home</h1>

			{allPosts.map(({ slug, title, excerpt, image }, index) => (
				<div
					key={index}
					style={{
						marginBottom: '5px',
						display: 'block',
						backgroundColor: 'red',
						width: '100%',
						height: '100%',
					}}
				>
					<Link href={`/posts/${slug}`}>
						<Image
							src={image.src}
							alt={image.description}
							width={200}
							height={200}
						/>
						<h2>{title}</h2>
					</Link>
					<p>{excerpt}</p>
				</div>
			))}
		</div>
	);
}

export async function getStaticProps() {
	const allPosts = getAllPosts(['slug', 'title', 'excerpt', 'image']);
	return {
		props: { allPosts },
	};
}
